### ISSUE TITLE
언라벨 음성 데이터 예측에 관해 질문이 있습니다.

### ISSUE THREAD

**Issue by qute012** [sooftware/End-to-end-Speech-Recognition#14]
안녕하세요.
![image](https://user-images.githubusercontent.com/33983084/80692539-ab6ae800-8b0c-11ea-8409-4813cab859d4.png)
Listener와 Speller를 이어주는 코드에서 Speller forward에서 target을 input으로 받게 되어있는데, 이 경우 언라벨된 음성을 추론하는 것은 불가능할까요?

**Comment by sooftware** [comment]
현재 코드 상에서는 <unk> (unknown) 토큰을 따로 사용하지 않기 때문에,  
레이블링 된 2,040개의 문자 중 하나로 무조건 나오게 됩니다.

**Comment by qute012** [comment]
질문을 잘 못 이해하신 것 같네요.
질문의 의도는 script가 없는 음성 추론은 구조상으로 안되는지요?

**Comment by sooftware** [comment]
아 방금 질문 이해했습니다 ㅎㅎ..  
   
보여주신 코드에서 input으로 target을 넣어주는 이유는  
Teacher Forcing을 사용하기 위함입니다.  
   
실제 추론시에는 Teacher Forcing을 사용하지 않기 때문에 target이 따로 필요하지 않습니다.  
   
그러므로 script가 없는 음성에 대해서도 추론이 가능합니다.

**Comment by qute012** [comment]
https://github.com/sooftware/End-to-end-Speech-Recognition/blob/d860f0f8274b977d13f0b1f2f6e44700d3bc0e8e/model/speller.py#L87-L89

위에 부분에서 target을 넘겨주지 않으면, 오류가 뜰텐데 따로 넘겨주는 방법이 있나요?

다음과 같이 패딩처리 되어있는 토큰으로 주는 것은 어떤지요.
![image](https://user-images.githubusercontent.com/33983084/80700948-8df04b00-8b19-11ea-8d38-4ecd7ce80271.png)

**Comment by sooftware** [comment]
아 말씀하신 작업을 전에 코드에서는 해놨었는데, 코드 수정하면서   
필요없는 코드라고 생각하고 없앤것 같네요.   
  
지적해신 부분 반영하겠습니다.    
감사합니다.

**Comment by qute012** [comment]
네. 감사합니다 ㅎㅎ

**Comment by sooftware** [comment]
코드 수정했고, push 해놓겠습니다 !! ㅎㅎ  
감사합니다.
