### ISSUE TITLE
beam search 에러

### ISSUE THREAD

**Issue by qute012** [sooftware/End-to-end-Speech-Recognition#15]
안녕하세요.
혹시 rnn cell을 LSTM으로 사용할 때 잘 돌아가시나요?

**Comment by sooftware** [comment]
덕진님 안녕하세요.  
빔서치 에러를 요즘 해결중에 있습니다.  
  
GRU에 대해서는 해결했습니다만, LSTM은 아직 테스트를 못해봤네요 ㅜ.ㅜ  
   
이 외에도, 빔서치를 적용했는데 Greedy 서치보다 성능이 안나와서 확인중에 있습니다.

**Comment by sooftware** [comment]
빔서치 코드를 조금 수정해서 다시 push 했습니다.  
LSTM으로 학습시킨 모델이 현재 없어서 테스트는 못해보고 있습니다.  ㅜ.ㅜ

**Comment by qute012** [comment]
저도 LSTM을 사용하여 빔서치 구현을 해보았는데 성능이 제대로 안나오네요. 낮게 나오기보다 그냥 엉망으로 나오는 듯 해요.

**Comment by sooftware** [comment]
저희는 gru에서 실험시에 그리디서치보다  
1~2퍼 낮은 정도의 수준을 보이고 있습니다.   
  
현재는 바빠서 디버깅을 못하고 있으나,   
length penalty 부분에 주목하고 있습니다.  
  
나온 결과값을 찍어봤을때 그리디 서치의 경우   
  
순우야 라고 끝나는데 반해   
빔서치의 경우 순우야야야야야야...  
  
와 같이 몇몇 문장이 평균적인 인식률을 현저히 떨어뜨리는 것을 확인했습니다.

**Comment by qute012** [comment]
혹시 다른 질문이지만 데이터 전부 다 SpecAugment를 적용하여 학습하고 계신가요?

**Comment by sooftware** [comment]
이전 학습까지는 실험중이여서 오그먼트를 off 하고 진행했으나, 현재 진행중인 학습은 모든 데이터에 오그멘테이션 적용중입니다.

2020년 5월 5일 (화) 오후 4:59, DeokJin <notifications@github.com>님이 작성:

**Comment by sooftware** [comment]
혹시 lstm으로 실험하셨다면, 어떤 하이퍼파라미터에서 어떤 결과가 나오셨는지 알 수 있을까요??

**Comment by qute012** [comment]
일단 프로젝트에서 rnn type을 lstm으로 사용할 때, beam search에서 hidden state를 inflate로 사용할 때, lstm의 hidden state와 cell state를 구분짓는 코드가 필요해보이네요.
https://github.com/sooftware/End-to-end-Speech-Recognition/blob/e55d0a8813a0d00088b67c7992dae5a6816254ed/model/beamsearch.py#L6-L11

혹시 teaching_force를 0.99로 모든 에폭을 훈련하셨는지요? 하이퍼파라미터를 본 프로젝트를 참고하여 사용하였는데 teaching_force를 0.99로 사용할 때 모델이 과적합하는걸로 보이네요. 그래서 저는 5에폭정도만 teaching_force=0.7로 학습하고 6에폭부터는 사용하지않고 학습하려해요.

저는 다른 오픈소스에서 beam search만 적용하여 lstm을 돌려보았는데 성능이 좋지않네요. 확인해보니 beam search의 문제는 아닌 듯 하고, 모델 학습이 제대로 되지않았네요. 다시 학습시켜서 beam search 테스트해보고 lstm에도 적용할 수 있도록 코드를 올려드릴게요. 혹시 개선된 내용이 있으면 공유해주시면 감사하겠습니다!

**Comment by sooftware** [comment]
저희 같은 경우는 학습 초기에 teacher_forcing_ratio를 0.99 혹은 1.0 정도로 높은 비율로 유지를 하다가, 어느 정도 학습 후에는 0.90 정도까지는 내리지만, 그 이하로는 내리지 않았습니다.  
    
학습초기에는 제대로된 추론을 하지 못하기 때문에, 티쳐포싱 비율을 높게 주는 것이 학습 가속화에도 좋고, 낮게 주게 되면 잘못된 입력이 들어가기 때문에 노이즈로 작용할 수도 있습니다.  
    
다만 추론시에는 티쳐포싱 사용이 불가능하기 때문에, 이러한 차이가 오류를 만들수도 있으나, 2019년에 발표된 논문에 따르면 이 차이는 크지 않다고 합니다. 저희 역시 여러 파라미터로 실험해본 결과, 티쳐포싱 비율을 높게 해주는 것이 성능에 도움이 많이 됐습니다.  
  
또한 과적합 문제는 전에 사용하신 zeroth 데이터셋을 사용하고 계시다면, 데이터셋이 작기 때문에 몇번의 에폭만으로도 쉽게 과적합이 될수도 있고, 과적합 문제는 SpecAugment를 주시면 많이 해결되리라고 생각합니다.  
  
관심가져주셔서 감사합니다.

**Comment by sooftware** [comment]
안녕하세요 덕진님.   
언급해주신, rnn cell이 lstm일 때, _inflate()하는 부분은 다음과 같이 수정했습니다.   
```python
if isinstance(h_state, tuple): 
    h_state = tuple([_inflate(h, self.k, 1) for h in h_state])
else:
    h_state = _inflate(h_state, self.k, 1)
```

**Comment by qute012** [comment]
네. 차후에 모델학습이 다되면 beam search를 다시 구현하여서 테스트해볼게요!
모델 구조를 조금 다르게 사용중인데 Ai-Hub 데이터를 학습 중인데, 현재 올려놓으신 github 프로젝트와 비교해보고싶은데 학습한 업데이트된 학습/훈련 기록을 공유해주실 수 있으신가요?

**Comment by sooftware** [comment]
저희가 그동안 모델 수정 및 이것저것 테스트를 하느라 1에폭만 돌리고 결과를 비교하는 일을 반복했습니다 :joy:  
  
이제 제대로 모델 하나 잡고 서버에서 돌리는 중입니다.  
첫번째 에폭만에 78.16%의 인식률이 나와줘서 현재 기대중에 있습니다 !!  
  
좋은 결과가 있다면 추후 깃허브에 업로드 및 하이퍼파라미터 모두 공개하겠습니다.   
덕진님도 좋은 결과가 있다면 알려주세요 !!  
  
감사합니다.
